pipeline {
    agent any
    // tools {
    //     maven "MAVEN3"
    //     jdk "oraclejdk8"
    // }

    environment {
        cluster = 'vproprod'
        service = 'vproappprodsvc'
    }

    stages {
        stage('Deploy to ECS prod'){ // This stage takes the image on ecr and pushes it to the ecs container
            steps {
                withAWS(credentials:'awscreds', region: 'us-east-1'){
                    sh 'aws ecs update-service --cluster ${cluster} --service ${service} --force-new-deployment'
                }

            }
        }
    }
}